version: '3'
services:
  react-client:
    container_name: react-client
    build:
      context: ./store-react-client
      dockerfile: Dockerfile
    volumes:
      - '.:/home/dyduch/store-react-client' 
      # - '/home/dyduch/store-react-client/node_modules'
    ports:
      - 12345:3000
    working_dir: /home/dyduch/store-react-client/
    command: bash -c "cd store-react-client && npm start"
  # play-server:
  #   build:
  #     context: ./store-play-server
  #     dockerfile: Dockerfile
  #   ports:
  #   - 12346:9000
  #   volumes:
  #    - '.:/home/dyduch/store-play-server'
  #   working_dir: /home/dyduch/store-play-server/